### ISSUE TITLE
Can't install plugin  on Arch Linux

### ISSUE THREAD

**Issue by Bitti09** [p3lim/screencloud-caddy#1]
Getting the following errors when i try to install it on Arch Linux:
1:

```
Error in file: /home/bitti/.local/share/screencloud/ScreenCloud/plugins/caddy/main.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/bitti/.local/share/screencloud/ScreenCloud/plugins/caddy/modules/pycaddy.py", line 1
    ../dist/pycaddy/pycaddy.py
    ^
SyntaxError: invalid syntax
```

2.:

```
Failed to call CaddyUpload.isConfigured()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'CaddyUpload'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'CaddyUpload' is not defined
```

**Comment by p3lim** [comment]
Github doesn't seem to package submodules, guess I'll have to do something else for releasing then.
